# Service Account Key authentication method
# See Authentication methods below for more config options
data_source covid:
  type: bigquery
  account_info_json_path: /usr/local/airflow/include/gcp/service_account.json
  auth_scopes:
  - https://www.googleapis.com/auth/bigquery
  - https://www.googleapis.com/auth/cloud-platform
  - https://www.googleapis.com/auth/drive
  project_id: 'airflow-project-aditya-405904'
  dataset: covid

soda_cloud:
  host: cloud.soda.io
  api_key_id: 
  api_key_secret: 
