# Note that only one of these targets is required

covid:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /usr/local/airflow/include/gcp/service_account.json
      project: airflow-project-aditya-405904
      dataset: covid # You can also use "schema" here
      threads: 1 # Must be a value of 1 or greater 
      timeout_seconds: 300
      location: US
